stack.o:	stackmain.o	push.o	pop.o	print.o
	gcc -o	stack.o	stackmain.o	push.o	pop.o	print.o
	gcc -c	stackmain.o	stackmain.c	push.h	pop.h	print.h
	gcc -c	push.o	push.h
	gcc -c	pop.o	pop.h
	gcc -c	print.o	print.h
	
